In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings 
warnings.filterwarnings('ignore')
%matplotlib inline

In [15]:


# Solution 1: Use double backslashes
df = pd.read_csv("Desktop\\machine learing\\titanic.csv")

# Solution 2: Use a raw string (prefix with r)
#df = pd.read_csv(r"Desktop\machine learing\titanic.csv")

# Solution 3: Use forward slashes (works in Windows)
#df = pd.read_csv("Desktop/machine learing/titanic.csv")

# Display the first few rows
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [17]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [19]:
df.nunique()

PassengerId    891
Survived         2
Pclass           3
Name           891
Sex              2
Age             88
SibSp            7
Parch            7
Ticket         681
Fare           248
Cabin          147
Embarked         3
dtype: int64

In [21]:
df.duplicated().sum()

0

In [23]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [41]:

df.drop(columns=['Cabin', 'Embarked'], inplace=True)

In [43]:
avg_age = df.Age.mean()
df.Age.replace(np.nan, avg_age, inplace = True)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833
2,3,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000
4,5,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500
...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.0000
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.0000
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,23.4500
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000
890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.7500

In [45]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
dtype: int64

In [47]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500

In [53]:
dummies = pd.get_dummies(df.Sex, dtype=int)
dummies

     female  male
0         0     1
1         1     0
2         1     0
3         1     0
4         0     1
..      ...   ...
886       0     1
887       1     0
888       1     0
889       0     1
890       0     1

[891 rows x 2 columns]

In [57]:
merged = pd.concat([df,dummies], axis='columns')
merged

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,female,male
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500,0,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,1,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,1,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,1,0
4,5,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.0000,0,1
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.0000,1,0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,23.4500,1,0
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000,0,1
890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.7500,0,1

In [77]:
final = merged.drop(['Name','Sex','Parch','Ticket','PassengerId','SibSp'], axis='columns')
final

     Survived  Pclass        Age     Fare  female  male
0           0       3  22.000000   7.2500       0     1
1           1       1  38.000000  71.2833       1     0
2           1       3  26.000000   7.9250       1     0
3           1       1  35.000000  53.1000       1     0
4           0       3  35.000000   8.0500       0     1
..        ...     ...        ...      ...     ...   ...
886         0       2  27.000000  13.0000       0     1
887         1       1  19.000000  30.0000       1     0
888         0       3  29.699118  23.4500       1     0
889         1       1  26.000000  30.0000       0     1
890         0       3  32.000000   7.7500       0     1

[891 rows x 6 columns]

In [79]:
input = final.drop('Survived', axis='columns')
input

     Pclass        Age     Fare  female  male
0         3  22.000000   7.2500       0     1
1         1  38.000000  71.2833       1     0
2         3  26.000000   7.9250       1     0
3         1  35.000000  53.1000       1     0
4         3  35.000000   8.0500       0     1
..      ...        ...      ...     ...   ...
886       2  27.000000  13.0000       0     1
887       1  19.000000  30.0000       1     0
888       3  29.699118  23.4500       1     0
889       1  26.000000  30.0000       0     1
890       3  32.000000   7.7500       0     1

[891 rows x 5 columns]

In [81]:
target = final.Survived
target

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [83]:
from sklearn import tree
model = tree.DecisionTreeClassifier()

In [85]:
model.fit(input, target)

DecisionTreeClassifier()

In [87]:
model.score(input,target)

0.9797979797979798

In [101]:
model.predict([[1,38,71,1,0]])

array([1], dtype=int64)

In [103]:
#now model after scallin ghe data
final

     Survived  Pclass        Age     Fare  female  male
0           0       3  22.000000   7.2500       0     1
1           1       1  38.000000  71.2833       1     0
2           1       3  26.000000   7.9250       1     0
3           1       1  35.000000  53.1000       1     0
4           0       3  35.000000   8.0500       0     1
..        ...     ...        ...      ...     ...   ...
886         0       2  27.000000  13.0000       0     1
887         1       1  19.000000  30.0000       1     0
888         0       3  29.699118  23.4500       1     0
889         1       1  26.000000  30.0000       0     1
890         0       3  32.000000   7.7500       0     1

[891 rows x 6 columns]

In [117]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
final[['Age','Fare']] = scaler.fit_transform(final[['Age','Fare']])

In [119]:
final

     Survived  Pclass       Age      Fare  female  male
0           0       3 -0.592481 -0.502445       0     1
1           1       1  0.638789  0.786845       1     0
2           1       3 -0.284663 -0.488854       1     0
3           1       1  0.407926  0.420730       1     0
4           0       3  0.407926 -0.486337       0     1
..        ...     ...       ...       ...     ...   ...
886         0       2 -0.207709 -0.386671       0     1
887         1       1 -0.823344 -0.044381       1     0
888         0       3  0.000000 -0.176263       1     0
889         1       1 -0.284663 -0.044381       0     1
890         0       3  0.177063 -0.492378       0     1

[891 rows x 6 columns]

In [121]:
x = input = final.drop('Survived', axis='columns')
x

     Pclass       Age      Fare  female  male
0         3 -0.592481 -0.502445       0     1
1         1  0.638789  0.786845       1     0
2         3 -0.284663 -0.488854       1     0
3         1  0.407926  0.420730       1     0
4         3  0.407926 -0.486337       0     1
..      ...       ...       ...     ...   ...
886       2 -0.207709 -0.386671       0     1
887       1 -0.823344 -0.044381       1     0
888       3  0.000000 -0.176263       1     0
889       1 -0.284663 -0.044381       0     1
890       3  0.177063 -0.492378       0     1

[891 rows x 5 columns]

In [125]:
y = final.Survived
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [139]:
from sklearn.model_selection import train_test_split

In [155]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.6)

In [157]:
from sklearn import tree
model = tree.DecisionTreeClassifier()

In [159]:
model.fit(x, y)

DecisionTreeClassifier()

In [161]:
model.score(x,y)

0.9797979797979798