Naive Bayes alogrithm 
Naive Bayes is a probabilistic machine learning alog based on bayes' Theorm it is particulary usefull for classification task and is widely used in text clasification spam filtering, sentiment ananysis(moveis review ), remmedendation system(amazon).
why is it called navie bayes

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings 
warnings.filterwarnings('ignore')
%matplotlib inline

In [30]:
df = pd.read_csv("Desktop\\machine learing\\titanic.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [32]:
df.nunique()

PassengerId    891
Survived         2
Pclass           3
Name           891
Sex              2
Age             88
SibSp            7
Parch            7
Ticket         681
Fare           248
Cabin          147
Embarked         3
dtype: int64

In [34]:
df.duplicated().sum()

0

In [36]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [40]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [42]:
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'], axis='columns', inplace=True)
df.head()

   Survived  Pclass     Sex   Age     Fare
0         0       3    male  22.0   7.2500
1         1       1  female  38.0  71.2833
2         1       3  female  26.0   7.9250
3         1       1  female  35.0  53.1000
4         0       3    male  35.0   8.0500

In [44]:
df.Age.isnull().sum()

177

In [50]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy='mean')
df[['Age']]= imputer.fit_transform(df[['Age']])
df.Age.isnull().sum()

0

In [72]:
inputs =df.drop('Survived', axis='columns')#independent variable
target= df.Survived#dependent

In [76]:
#input.Sex = input.Sex.map({'male':1, 'female':2})

In [82]:
dummies = pd.get_dummies(inputs.Sex ,dtype='int')
dummies.head(3)

   female  male
0       0     1
1       1     0
2       1     0

In [86]:
inputs = pd.concat([inputs,dummies], axis='columns')
inputs.head()

   Pclass     Sex   Age     Fare  female  male  female  male
0       3    male  22.0   7.2500       0     1       0     1
1       1  female  38.0  71.2833       1     0       1     0
2       3  female  26.0   7.9250       1     0       1     0
3       1  female  35.0  53.1000       1     0       1     0
4       3    male  35.0   8.0500       0     1       0     1

In [88]:
inputs.drop(['Sex', 'male'],axis='columns',inplace=True)# male drop due to dummy vaiable tarp thearoy
inputs.head()

   Pclass   Age     Fare  female  female
0       3  22.0   7.2500       0       0
1       1  38.0  71.2833       1       1
2       3  26.0   7.9250       1       1
3       1  35.0  53.1000       1       1
4       3  35.0   8.0500       0       0

In [92]:
inputs.columns[inputs.isna().any()]

Index([], dtype='object')

In [ ]:
#inputs.Age= input.fillna(inputs.Age.mean()
#inputs.head()

In [110]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(inputs, target, test_size=0.3)#70 percent train 30%tes

In [116]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [118]:
model.fit(x_train, y_train)

GaussianNB()

In [120]:
model.score(x_test,y_test)

0.7761194029850746

In [ ]:
x_test[0:10]

In [126]:
model.predict(x_test[0:10])

array([1, 1, 1, 1, 0, 1, 1, 0, 0, 0], dtype=int64)

In [ ]:
model.predict_prod

calculate the score using corss validation

In [131]:
from sklearn.model_selection import cross_val_score
cross_val_score(GaussianNB(),x_train, y_train, cv=5)

array([0.816     , 0.752     , 0.784     , 0.72580645, 0.84677419])

In [135]:
from sklearn import tree
model1 = tree.DecisionTreeClassifier()

In [139]:
model.fit(x_train,y_train)

DecisionTreeClassifier()

In [143]:
model.score(x_test,y_test)

0.7723880597014925

In [153]:
from sklearn.linear_model import LogisticRegression#LG
log_reg= LogisticRegression()
log_reg.fit(x_train,y_train)

LogisticRegression()

In [155]:
model.score(x_test,y_test)

0.7723880597014925

In [179]:
from sklearn.neighbors import KNeighborsClassifier #kNN
knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(x_train, y_train)
model.score(x_test, y_test)

0.7723880597014925

In [185]:
from sklearn.svm import SVC #SVM
svc = SVC(kernel='linear')
svc.fit(x_train, y_train)
model.score(x_test, y_test)

0.7723880597014925

In [191]:
svc_pred = svc.predict(x_test)
accuracy_score(y_test, svc_pred)

NameError: name 'accuracy_score' is not defined